"""Init

Revision ID: 038de52d5c41
Revises: 
Create Date: 2023-12-13 12:36:19.212589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038de52d5c41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
